// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';

export function DetectLocation():Promise<main.LocationResult>;

export function GetCities():Promise<Array<main.City>>;

export function GetConfig():Promise<main.Config>;

export function GetLang():Promise<string>;

export function GetState():Promise<main.State>;

export function GetVersion():Promise<string>;

export function SaveConfig(arg1:main.Config):Promise<void>;

export function SetAutoStart(arg1:boolean):Promise<void>;

export function SetCloseTray(arg1:boolean):Promise<void>;

export function SetEnabled(arg1:boolean):Promise<void>;

export function SetLang(arg1:string):Promise<void>;

export function SetManualTheme(arg1:string):Promise<void>;

export function ShowWindow():Promise<void>;
