// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function DetectLocation() {
  return window['go']['main']['App']['DetectLocation']();
}

export function GetCities() {
  return window['go']['main']['App']['GetCities']();
}

export function GetConfig() {
  return window['go']['main']['App']['GetConfig']();
}

export function GetLang() {
  return window['go']['main']['App']['GetLang']();
}

export function GetState() {
  return window['go']['main']['App']['GetState']();
}

export function GetVersion() {
  return window['go']['main']['App']['GetVersion']();
}

export function SaveConfig(arg1) {
  return window['go']['main']['App']['SaveConfig'](arg1);
}

export function SetAutoStart(arg1) {
  return window['go']['main']['App']['SetAutoStart'](arg1);
}

export function SetCloseTray(arg1) {
  return window['go']['main']['App']['SetCloseTray'](arg1);
}

export function SetEnabled(arg1) {
  return window['go']['main']['App']['SetEnabled'](arg1);
}

export function SetLang(arg1) {
  return window['go']['main']['App']['SetLang'](arg1);
}

export function SetManualTheme(arg1) {
  return window['go']['main']['App']['SetManualTheme'](arg1);
}

export function ShowWindow() {
  return window['go']['main']['App']['ShowWindow']();
}
